### ISSUE TITLE
Why not working?

### ISSUE THREAD

**Issue by tahaluindo** [TgCatUB/nekopack#50]
![Screenshot_2022-05-14-02-47-23-05](https://user-images.githubusercontent.com/94370774/168379380-a4f7642a-3f42-4301-a4b6-e9d6ee4ab21a.png)

**Comment by Jisan09** [comment]
Fork nekopack with different name & then deploy from your fork.
For more info join support group & type #tutorial

**Comment by tahaluindo** [comment]
thanks you for support
